#!/bin/bash

source ~/.bin/gerrit-review-dashboard/.venv/bin/activate

QUERY=`cat ~/.bin/salmon-gerrit-query.txt`

python2 ~/.bin/gerrit-review-dashboard/dashboard.py \
-u gibi \
-P 454nwcl9jhke \
-r 60 \
-q "$QUERY"

deactivate
